import { PokemonSet } from '@pkmn/sim';
import { BattleScenario } from './teams.js';

function set(overrides: Partial<PokemonSet> & { species: string; moves: string[] }): PokemonSet {
  return {
    name: overrides.species, species: overrides.species,
    item: overrides.item || '', ability: overrides.ability || '',
    moves: overrides.moves, nature: overrides.nature || 'Serious',
    evs: overrides.evs || { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
    ivs: overrides.ivs || { hp: 31, atk: 31, def: 31, spa: 31, spd: 31, spe: 31 },
    level: overrides.level || 100, gender: overrides.gender || '',
    shiny: false, happiness: 255, pokeball: '', hpType: '',
    dynamaxLevel: 10, teraType: overrides.teraType || '', gigantamax: false,
  };
}

export const batch4Scenarios: BattleScenario[] = [
  // === DEFENSIVE ABILITIES ===
  {
    id: 'def-multiscale',
    description: 'Multiscale halves damage at full HP',
    seed: [3500, 3501, 3502, 3503],
    p1: [set({ species: 'Weavile', ability: 'Pressure', item: '', moves: ['Ice Punch', 'Knock Off', 'Ice Shard', 'Low Kick'], nature: 'Jolly', evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 } })],
    p2: [set({ species: 'Dragonite', ability: 'Multiscale', item: '', moves: ['Outrage', 'Extreme Speed', 'Earthquake', 'Fire Punch'], nature: 'Adamant', evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 } })],
    turns: [['move 1', 'move 2']],
  },
  {
    id: 'def-thick-fat',
    description: 'Thick Fat halves Fire and Ice damage',
    seed: [3510, 3511, 3512, 3513],
    p1: [set({ species: 'Volcarona', ability: 'Flame Body', item: '', moves: ['Fire Blast', 'Bug Buzz', 'Psychic', 'Quiver Dance'], nature: 'Timid', evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 } })],
    p2: [set({ species: 'Snorlax', ability: 'Thick Fat', item: '', moves: ['Body Slam', 'Earthquake', 'Rest', 'Sleep Talk'], nature: 'Careful', evs: { hp: 252, atk: 0, def: 4, spa: 0, spd: 252, spe: 0 } })],
    turns: [['move 1', 'move 1']],
  },
  {
    id: 'def-ice-scales-special',
    description: 'Ice Scales halves special damage',
    seed: [3520, 3521, 3522, 3523],
    p1: [set({ species: 'Alakazam', ability: 'Magic Guard', item: '', moves: ['Psychic', 'Shadow Ball', 'Focus Blast', 'Energy Ball'], nature: 'Timid', evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 } })],
    p2: [set({ species: 'Frosmoth', ability: 'Ice Scales', item: '', moves: ['Ice Beam', 'Bug Buzz', 'Hurricane', 'Quiver Dance'], nature: 'Timid', evs: { hp: 252, atk: 0, def: 0, spa: 252, spd: 4, spe: 0 } })],
    turns: [['move 1', 'move 1']],
  },
  {
    id: 'def-fur-coat-physical',
    description: 'Fur Coat doubles effective Def',
    seed: [3530, 3531, 3532, 3533],
    p1: [set({ species: 'Garchomp', ability: 'Rough Skin', item: '', moves: ['Earthquake', 'Dragon Claw', 'Stone Edge', 'Swords Dance'], nature: 'Jolly', evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 } })],
    p2: [set({ species: 'Furfrou', ability: 'Fur Coat', item: '', moves: ['Return', 'Wild Charge', 'U-turn', 'Cotton Guard'], nature: 'Impish', evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 } })],
    turns: [['move 1', 'move 1']],
  },
  {
    id: 'def-filter-super-eff',
    description: 'Filter/Solid Rock 0.75x on super effective',
    seed: [3540, 3541, 3542, 3543],
    p1: [set({ species: 'Lucario', ability: 'Inner Focus', item: '', moves: ['Close Combat', 'Meteor Mash', 'Extreme Speed', 'Swords Dance'], nature: 'Adamant', evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 } })],
    p2: [set({ species: 'Rhyperior', ability: 'Solid Rock', item: '', moves: ['Earthquake', 'Stone Edge', 'Megahorn', 'Stealth Rock'], nature: 'Adamant', evs: { hp: 252, atk: 252, def: 0, spa: 0, spd: 4, spe: 0 } })],
    turns: [['move 1', 'move 1']],
  },
  // === ITEMS ===
  {
    id: 'item-choice-band',
    description: 'Choice Band 1.5x physical Atk',
    seed: [3600, 3601, 3602, 3603],
    p1: [set({ species: 'Garchomp', ability: 'Rough Skin', item: 'Choice Band', moves: ['Earthquake', 'Dragon Claw', 'Stone Edge', 'Fire Fang'], nature: 'Jolly', evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 } })],
    p2: [set({ species: 'Blissey', ability: 'Natural Cure', item: '', moves: ['Seismic Toss', 'Soft-Boiled', 'Thunder Wave', 'Toxic'], nature: 'Bold', evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 } })],
    turns: [['move 1', 'move 1']],
  },
  {
    id: 'item-choice-specs',
    description: 'Choice Specs 1.5x special SpA',
    seed: [3610, 3611, 3612, 3613],
    p1: [set({ species: 'Gengar', ability: 'Cursed Body', item: 'Choice Specs', moves: ['Sludge Bomb', 'Shadow Ball', 'Focus Blast', 'Thunderbolt'], nature: 'Timid', evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 } })],
    p2: [set({ species: 'Blissey', ability: 'Natural Cure', item: '', moves: ['Seismic Toss', 'Soft-Boiled', 'Thunder Wave', 'Toxic'], nature: 'Bold', evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 } })],
    turns: [['move 1', 'move 1']],
  },
  {
    id: 'item-life-orb',
    description: 'Life Orb 1.3x damage (5324/4096)',
    seed: [3620, 3621, 3622, 3623],
    p1: [set({ species: 'Garchomp', ability: 'Rough Skin', item: 'Life Orb', moves: ['Earthquake', 'Dragon Claw', 'Stone Edge', 'Swords Dance'], nature: 'Jolly', evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 } })],
    p2: [set({ species: 'Blissey', ability: 'Natural Cure', item: '', moves: ['Seismic Toss', 'Soft-Boiled', 'Thunder Wave', 'Toxic'], nature: 'Bold', evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 } })],
    turns: [['move 1', 'move 1']],
  },
  {
    id: 'item-expert-belt-se',
    description: 'Expert Belt 1.2x on super effective only',
    seed: [3630, 3631, 3632, 3633],
    p1: [set({ species: 'Lucario', ability: 'Inner Focus', item: 'Expert Belt', moves: ['Close Combat', 'Meteor Mash', 'Extreme Speed', 'Swords Dance'], nature: 'Adamant', evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 } })],
    p2: [set({ species: 'Snorlax', ability: 'Thick Fat', item: '', moves: ['Body Slam', 'Earthquake', 'Rest', 'Sleep Talk'], nature: 'Careful', evs: { hp: 252, atk: 0, def: 4, spa: 0, spd: 252, spe: 0 } })],
    turns: [['move 1', 'move 1']],
  },
  {
    id: 'item-mystic-water',
    description: 'Mystic Water 1.2x Water moves',
    seed: [3640, 3641, 3642, 3643],
    p1: [set({ species: 'Starmie', ability: 'Natural Cure', item: 'Mystic Water', moves: ['Surf', 'Ice Beam', 'Thunderbolt', 'Psychic'], nature: 'Timid', evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 } })],
    p2: [set({ species: 'Blissey', ability: 'Natural Cure', item: '', moves: ['Seismic Toss', 'Soft-Boiled', 'Thunder Wave', 'Toxic'], nature: 'Bold', evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 } })],
    turns: [['move 1', 'move 1']],
  },
  {
    id: 'item-muscle-band',
    description: 'Muscle Band 1.1x physical moves',
    seed: [3650, 3651, 3652, 3653],
    p1: [set({ species: 'Garchomp', ability: 'Rough Skin', item: 'Muscle Band', moves: ['Earthquake', 'Dragon Claw', 'Stone Edge', 'Swords Dance'], nature: 'Jolly', evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 } })],
    p2: [set({ species: 'Blissey', ability: 'Natural Cure', item: '', moves: ['Seismic Toss', 'Soft-Boiled', 'Thunder Wave', 'Toxic'], nature: 'Bold', evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 } })],
    turns: [['move 1', 'move 1']],
  },
  {
    id: 'item-wise-glasses',
    description: 'Wise Glasses 1.1x special moves',
    seed: [3660, 3661, 3662, 3663],
    p1: [set({ species: 'Gengar', ability: 'Cursed Body', item: 'Wise Glasses', moves: ['Sludge Bomb', 'Shadow Ball', 'Focus Blast', 'Thunderbolt'], nature: 'Timid', evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 } })],
    p2: [set({ species: 'Blissey', ability: 'Natural Cure', item: '', moves: ['Seismic Toss', 'Soft-Boiled', 'Thunder Wave', 'Toxic'], nature: 'Bold', evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 } })],
    turns: [['move 1', 'move 1']],
  },
  // === CRIT + BURN + SCREENS + BOOSTS ===
  {
    id: 'crit-ignores-neg-atk-boost',
    description: 'Crit ignores attacker negative boosts and defender positive boosts',
    seed: [3700, 3701, 3702, 3703],
    p1: [set({ species: 'Kingambit', ability: 'Supreme Overlord', item: '', moves: ['Kowtow Cleave', 'Sucker Punch', 'Iron Head', 'Swords Dance'], nature: 'Adamant', evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 } })],
    p2: [set({ species: 'Ferrothorn', ability: 'Iron Barbs', item: '', moves: ['Power Whip', 'Knock Off', 'Iron Defense', 'Leech Seed'], nature: 'Relaxed', evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 } })],
    turns: [['move 1', 'move 3'], ['move 1', 'move 3']],
  },
  {
    id: 'burn-halves-phys-no-guts',
    description: 'Burn halves physical damage (non-Guts, non-Facade)',
    seed: [3710, 3711, 3712, 3713],
    p1: [set({ species: 'Garchomp', ability: 'Rough Skin', item: '', moves: ['Earthquake', 'Dragon Claw', 'Stone Edge', 'Swords Dance'], nature: 'Jolly', evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 } })],
    p2: [set({ species: 'Rotom-Wash', ability: 'Levitate', item: '', moves: ['Will-O-Wisp', 'Volt Switch', 'Hydro Pump', 'Pain Split'], nature: 'Bold', evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 } })],
    turns: [['move 2', 'move 1'], ['move 2', 'move 3']],
  },
  {
    id: 'screen-reflect-physical',
    description: 'Reflect halves physical damage (non-crit)',
    seed: [3720, 3721, 3722, 3723],
    p1: [set({ species: 'Garchomp', ability: 'Rough Skin', item: '', moves: ['Earthquake', 'Dragon Claw', 'Stone Edge', 'Swords Dance'], nature: 'Jolly', evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 } })],
    p2: [set({ species: 'Grimmsnarl', ability: 'Prankster', item: '', moves: ['Reflect', 'Light Screen', 'Spirit Break', 'Thunder Wave'], nature: 'Careful', evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 0, spe: 4 } })],
    turns: [['move 2', 'move 1'], ['move 1', 'move 3']],
  },
  {
    id: 'screen-light-screen-special',
    description: 'Light Screen halves special damage (non-crit)',
    seed: [3730, 3731, 3732, 3733],
    p1: [set({ species: 'Gengar', ability: 'Cursed Body', item: '', moves: ['Shadow Ball', 'Sludge Bomb', 'Focus Blast', 'Thunderbolt'], nature: 'Timid', evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 } })],
    p2: [set({ species: 'Grimmsnarl', ability: 'Prankster', item: '', moves: ['Reflect', 'Light Screen', 'Spirit Break', 'Thunder Wave'], nature: 'Careful', evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 0, spe: 4 } })],
    turns: [['move 4', 'move 2'], ['move 1', 'move 3']],
  },
  {
    id: 'boost-swords-dance-atk',
    description: '+2 Atk from Swords Dance then attack',
    seed: [3740, 3741, 3742, 3743],
    p1: [set({ species: 'Garchomp', ability: 'Rough Skin', item: '', moves: ['Swords Dance', 'Earthquake', 'Dragon Claw', 'Stone Edge'], nature: 'Jolly', evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 } })],
    p2: [set({ species: 'Blissey', ability: 'Natural Cure', item: '', moves: ['Seismic Toss', 'Soft-Boiled', 'Thunder Wave', 'Toxic'], nature: 'Bold', evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 } })],
    turns: [['move 1', 'move 2'], ['move 2', 'move 1']],
  },
  {
    id: 'multi-hit-icicle-spear',
    description: 'Multi-hit Icicle Spear (Skill Link = 5 hits)',
    seed: [3750, 3751, 3752, 3753],
    p1: [set({ species: 'Cloyster', ability: 'Skill Link', item: '', moves: ['Icicle Spear', 'Rock Blast', 'Hydro Pump', 'Shell Smash'], nature: 'Jolly', evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 } })],
    p2: [set({ species: 'Garchomp', ability: 'Rough Skin', item: '', moves: ['Earthquake', 'Dragon Claw', 'Stone Edge', 'Swords Dance'], nature: 'Jolly', evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 } })],
    turns: [['move 1', 'move 1']],
  },
];
